name: build-push

on:
  workflow_call:
    inputs: 
      docker_user_name:
        description: "Username to login to DockerHub"
        type: string
        required: true
      dockerhub_repo:
        description: "Dockerhub repo"
        type: string
        required: true
      dockerfile:
        description: "Dockerfile"
        type: string
        required: true
    secrets:
      docker_access_token:
        required: true

jobs:
  build-docker:
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_user_name }}
          password: ${{ secrets.docker_access_token }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Choose tags

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.docker_user_name }}/${{ inputs.dockerhub_repo}}
          tags: |
            ${{inputs.iamge_tag}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{inputs.dockerfile}}
